api_keys:
  deepseek: sk-be719786e9844c1b8385727045975885
  google: AIzaSyC399S3ImK3BILm2WhVRQnTkIdDYv0Shd0
  zhipu: "123"
backup_model: glm-4-flash
default_model: deepseek-chat
provider_templates:
  deepseek:
    api_param: deepseek_api_key
    env_var: DEEPSEEK_API_KEY
    temperature: 0.7
  google:
    api_param: google_api_key
    env_var: GOOGLE_API_KEY
    temperature: 0.7
  zhipu:
    api_param: api_key
    env_var: ZHIPUAI_API_KEY
    temperature: 0.7
providers:
  deepseek:
    models:
      - deepseek-chat
      - deepseek-reasoner
  google:
    models:
      - gemini-2.0-flash
      - gemini-2.5-flash-preview-04-17
      - gemini-2.5-pro-exp-03-25
  zhipu:
    models:
      - glm-4-flash
proxy:
  http: ""
  https: ""
